# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# CentOS Stream 10 distribution configuration.
# Applied automatically when Distribution=centos is selected.

[Match]
Distribution=centos

[Distribution]
Release=10

[Content]
WithRecommends=yes
Packages=
	NetworkManager
	NetworkManager-wifi
	atheros-firmware
	bash
	bluez
	coreutils
	dosfstools
	dracut
	e2fsprogs
	fwupd
	kernel
	iproute
	kmod
	linux-firmware
	openssh-clients
	openssh-server
	pciutils
	pipewire
	podman
	qcom-firmware
	rfkill
	sudo
	systemd
	systemd-boot
	usbutils
	v4l-utils
	vim-minimal
	wget
	wireless-regdb
	wpa_supplicant


