name = "cs-stream-console-aarch64"
description = "CentOS Stream ARM64 console image with baseline packages (NetworkManager, ssh, bluetooth, pipewire, etc.)"
version = "0.0.2"
distro = "centos-10"

packages = [
  {name = "bluez",            version = "*"},
  {name = "dosfstools",       version = "*"},
  {name = "e2fsprogs",        version = "*"},
  {name = "fwupd",            version = "*"},
  {name = "NetworkManager",   version = "*"},
  {name = "NetworkManager-wifi",           version = "*"},
  {name = "openssh-clients",  version = "*"},
  {name = "openssh-server",   version = "*"},
  {name = "pciutils",         version = "*"},
  {name = "pipewire",         version = "*"},
  {name = "podman",           version = "*"},
  {name = "rfkill",           version = "*"},
  {name = "sudo",             version = "*"},
  {name = "usbutils",         version = "*"},
  {name = "v4l-utils",        version = "*"},
  {name = "vim",              version = "*"},
  {name = "wget",             version = "*"},
  {name = "wireless-regdb",   version = "*"},
  {name = "wpa_supplicant",   version = "*"},

  # --- Kernel prerequisites ---
  {name = "dracut",           version = "*"},
  {name = "kmod",             version = "*"},

  # --- Firmware ---
  {name = "linux-firmware",   version = "*"},
  {name = "qcom-firmware",    version = "*"},
  {name = "atheros-firmware", version = "*"},

  {name = "systemd",          version = "*"},
  {name = "kernel",           version = "*"},
]

[[customizations.repositories]]
id = "local-qcom-kernel"
name = "RHEL 9 RT Repo"
baseurls = ["http://10.37.19.114:8000/mock-fedora-builder/"]
enabled = true
gpgcheck = false

[customizations.kernel]
append = "clk_ignore_unused pd_ignore_unused audit=0 deferred_probe_timeout=30 console=ttyMSM0,115200 qcom_scm.download_mode=1"

# Disk layout (raw/plain partitions).
[[customizations.disk.partitions]]
type = "plain"
mountpoint = "/boot/efi"
fs_type = "vfat"
label = "ESP"
minsize = "512 MiB"

[[customizations.disk.partitions]]
type = "plain"
mountpoint = "/"
fs_type = "ext4"
label = "root"
minsize = "8 GiB"

[customizations]
hostname = "centos"

[customizations.services]
enabled = ["sshd", "NetworkManager"]

[[customizations.user]]
name = "qcom"
password = "qcom"
groups = ["wheel", "adm", "audio", "render", "users", "video"]
