#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
"""
patch_manifest.py

Post-processes an osbuild v2 manifest generated by image-builder-cli to
replace the 'image' and 'qcow2' pipelines with four new pipelines that
emit efi.bin and rootfs.img as direct raw-image artifacts — no qcow2
conversion, no post-processing extraction.

New pipelines injected
----------------------
efi-image
  • org.osbuild.truncate  — allocate efi.bin (EFI_SIZE_MiB)
  • org.osbuild.mkfs.fat  — FAT32 via loopback with sector-size=4096 (UFS)
  • org.osbuild.copy      — populate from the 'os' tree's /boot/efi/

rootfs-image
  • org.osbuild.truncate  — allocate rootfs.img (ROOT_SIZE_GiB)
  • org.osbuild.mkfs.ext4 — ext4 with the rootfs UUID from the 'os' pipeline
  • org.osbuild.copy      — populate from the full 'os' tree

efi-artifact
  • org.osbuild.tar       — export efi.bin as a bare file

rootfs-artifact
  • org.osbuild.tar       — export rootfs.img as a bare file
"""

import argparse
import json
import re
import sys
import uuid


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_pipeline(pipelines: list, name: str) -> dict | None:
    for p in pipelines:
        if p.get("name") == name:
            return p
    return None


def extract_rootfs_uuid(pipelines: list) -> str:
    """
    Pull the rootfs UUID from the kernel-cmdline stage in the 'os' pipeline.
    Falls back to a freshly generated UUID if not found.
    """
    os_pipe = find_pipeline(pipelines, "os")
    if os_pipe:
        for stage in os_pipe.get("stages", []):
            if stage.get("type") == "org.osbuild.kernel-cmdline":
                uid = stage.get("options", {}).get("root_fs_uuid", "")
                if uid:
                    return uid
    return str(uuid.uuid4())


def extract_efi_volid(pipelines: list) -> str:
    """
    Pull the EFI volume ID from the mkfs.fat stage in the original 'image'
    pipeline.  Falls back to a random 8-hex-char ID.
    """
    img_pipe = find_pipeline(pipelines, "image")
    if img_pipe:
        for stage in img_pipe.get("stages", []):
            if stage.get("type") == "org.osbuild.mkfs.fat":
                volid = stage.get("options", {}).get("volid", "")
                if volid:
                    return volid
    return uuid.uuid4().hex[:8].upper()


def sectors(mib: int) -> int:
    """Convert MiB to 512-byte sectors (used by org.osbuild.truncate)."""
    return mib * 1024 * 1024 // 512


def bytes_from_mib(mib: int) -> int:
    return mib * 1024 * 1024


def bytes_from_gib(gib: int) -> int:
    return gib * 1024 * 1024 * 1024


# ---------------------------------------------------------------------------
# Pipeline builders
# ---------------------------------------------------------------------------

def make_efi_image_pipeline(efi_size_mib: int, efi_volid: str) -> dict:
    """
    Allocate a raw FAT32 image (efi.bin) with 4096-byte logical sectors
    (required for UFS devices) and populate it from the 'os' tree's
    /boot/efi/ subtree.
    """
    efi_bytes = bytes_from_mib(efi_size_mib)
    return {
        "name": "efi-image",
        "build": "name:build",
        "stages": [
            # 1. Allocate the raw image file
            {
                "type": "org.osbuild.truncate",
                "options": {
                    "filename": "efi.bin",
                    "size": str(efi_bytes)
                }
            },
            # 2. Format as FAT32 with 4096-byte logical sectors via loopback.
            #    The loopback device's sector-size=4096 causes mkfs.fat to
            #    write a BPB bytes-per-sector of 4096, which is required for
            #    the Linux FAT driver to mount the image on UFS (4K LBA).
            {
                "type": "org.osbuild.mkfs.fat",
                "options": {
                    "volid": efi_volid,
                    "label": "ESP",
                    "fat-size": 32
                },
                "devices": {
                    "device": {
                        "type": "org.osbuild.loopback",
                        "options": {
                            "filename": "efi.bin",
                            "sector-size": 4096
                        }
                    }
                }
            },
            # 3. Copy /boot/efi/ contents from the 'os' tree into the image
            {
                "type": "org.osbuild.copy",
                "inputs": {
                    "os-tree": {
                        "type": "org.osbuild.tree",
                        "origin": "org.osbuild.pipeline",
                        "references": ["name:os"]
                    }
                },
                "options": {
                    "paths": [
                        {
                            "from": "input://os-tree/boot/efi/",
                            "to": "mount://efi-device/"
                        }
                    ]
                },
                "devices": {
                    "efi-device": {
                        "type": "org.osbuild.loopback",
                        "options": {
                            "filename": "efi.bin",
                            "sector-size": 4096
                        }
                    }
                },
                "mounts": [
                    {
                        "name": "efi-device",
                        "type": "org.osbuild.fat",
                        "source": "efi-device",
                        "target": "/"
                    }
                ]
            }
        ]
    }


def make_rootfs_image_pipeline(root_size_gib: int, rootfs_uuid: str) -> dict:
    """
    Allocate a raw ext4 image (rootfs.img) and populate it from the full
    'os' tree.
    """
    root_bytes = bytes_from_gib(root_size_gib)
    return {
        "name": "rootfs-image",
        "build": "name:build",
        "stages": [
            # 1. Allocate the raw image file
            {
                "type": "org.osbuild.truncate",
                "options": {
                    "filename": "rootfs.img",
                    "size": str(root_bytes)
                }
            },
            # 2. Format as ext4
            {
                "type": "org.osbuild.mkfs.ext4",
                "options": {
                    "uuid": rootfs_uuid,
                    "label": "root"
                },
                "devices": {
                    "device": {
                        "type": "org.osbuild.loopback",
                        "options": {
                            "filename": "rootfs.img"
                        }
                    }
                }
            },
            # 3. Copy the full 'os' tree into the image
            {
                "type": "org.osbuild.copy",
                "inputs": {
                    "os-tree": {
                        "type": "org.osbuild.tree",
                        "origin": "org.osbuild.pipeline",
                        "references": ["name:os"]
                    }
                },
                "options": {
                    "paths": [
                        {
                            "from": "input://os-tree/",
                            "to": "mount://root-device/"
                        }
                    ]
                },
                "devices": {
                    "root-device": {
                        "type": "org.osbuild.loopback",
                        "options": {
                            "filename": "rootfs.img"
                        }
                    }
                },
                "mounts": [
                    {
                        "name": "root-device",
                        "type": "org.osbuild.ext4",
                        "source": "root-device",
                        "target": "/"
                    }
                ]
            }
        ]
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Patch an osbuild manifest to emit efi.bin + rootfs.img directly"
    )
    parser.add_argument("--input",     required=True, help="Input manifest JSON")
    parser.add_argument("--output",    required=True, help="Output patched manifest JSON")
    parser.add_argument("--efi-size",  type=int, default=512,
                        help="EFI partition size in MiB (default: 512)")
    parser.add_argument("--root-size", type=int, default=8,
                        help="rootfs size in GiB (default: 8)")
    args = parser.parse_args()

    with open(args.input) as f:
        manifest = json.load(f)

    pipelines = manifest.get("pipelines", [])

    # Extract UUIDs / vol-IDs from the generated manifest so they stay
    # consistent with what image-builder-cli wrote into /etc/fstab and
    # the kernel command line.
    rootfs_uuid = extract_rootfs_uuid(pipelines)
    efi_volid   = extract_efi_volid(pipelines)

    print(f"[*] rootfs UUID : {rootfs_uuid}")
    print(f"[*] EFI vol-id  : {efi_volid}")

    # Remove the 'image' and 'qcow2' pipelines
    pipelines = [p for p in pipelines if p.get("name") not in ("image", "qcow2")]

    # Append the two new image pipelines.
    # osbuild --export efi-image   → /output/efi-image/efi.bin
    # osbuild --export rootfs-image → /output/rootfs-image/rootfs.img
    # No tar wrapper needed: --export copies the pipeline tree directly.
    pipelines.append(make_efi_image_pipeline(args.efi_size, efi_volid))
    pipelines.append(make_rootfs_image_pipeline(args.root_size, rootfs_uuid))

    manifest["pipelines"] = pipelines

    with open(args.output, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[*] Patched manifest written → {args.output}")
    print(f"    Pipelines: {[p['name'] for p in pipelines]}")


if __name__ == "__main__":
    main()
