name: Nightly Build

on:
  workflow_dispatch:
  schedule:
  # NOTE - changes to the cron spec should be pushed by https://github.com/quic-yocto-ci
  # so that build notification emails will be sent out properly.
  # At 0:22 UTC everyday - picked a random "minute" as top of hour can be busy in github
  - cron: "22 0 * * *"

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build-nightly:
    uses: ./.github/workflows/build-rpm.yml
